-- Construção da DDL
-- Exercício Guiado CRUD Aula 10

CREATE DATABASE	IF NOT EXISTS CARDAPIO;
USE CARDAPIO;

-- INICIAR A CRIAÇÃO DE TABELAS POR QUEM NÃO TEM FK
-- -------------------------

-- -------------------------
-- CRIAÇÃO TABELA CATEGORIA
-- -------------------------
CREATE TABLE CATEGORIA(
	ID_CATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    URL_IMAGEM varchar(255) 
);

-- -------------------------
-- CRIAÇÃO TABELA CLIENTE
-- -------------------------
CREATE TABLE CLIENTE(
	ID_CLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
    SOBRENOME VARCHAR(100),
    CPF VARCHAR(15),
    NR_CELULAR VARCHAR(20),
    EMAIL VARCHAR(100)
);

-- -------------------------
-- CRIAÇÃO TABELA PRODUTOS
-- -------------------------
CREATE TABLE PRODUTO(
	ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CATEGORIA INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    IMAGEM VARCHAR(255),
    VALOR_PRODUTO DECIMAL(5,2),
    CONSTRAINT FK_PRODUTO_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
    );
    
-- -------------------------
-- CRIAÇÃO TABELA CONTA
-- -------------------------
CREATE TABLE CONTA(
	ID_CONTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    DATA_HORA_CONTA DATETIME DEFAULT CURRENT_TIMESTAMP,
    VALOR_TOTAL DECIMAL(5,2),
    CONSTRAINT FK_CONTA_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- -------------------------
-- CRIAÇÃO TABELA PEDIDOS
-- -------------------------
CREATE TABLE PEDIDO(
	ID_PEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ID_CLIENTE INT NOT NULL,
    ID_PRODUTO INT NOT NULL,
    QUANTIDADE INT,
    PRECO_TOTAL DECIMAL(5,2),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_PEDIDO_PRODUTO FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);

