-- CRIACAO DDL E DER DH_TUBE
-- MESA 2:	FILIPE CUSTODIO, FELIPE TONIOLO, RODRIGO ARAÚJO, ALLAN MEDEIROS

CREATE DATABASE IF NOT EXISTS DHTUBE;
USE DHTUBE;

CREATE TABLE AVATAR(
	ID_AVATAR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    URL_IMAGEM VARCHAR(100)
);

CREATE TABLE PAIS(
	ID_PAIS INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100)
);

CREATE TABLE USUARIO(
	ID_USUARIO INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(45),
    email VARCHAR(45),
    senha VARCHAR(45),
    dataNascimento DATETIME,
    CEP VARCHAR(45),
    ID_PAIS INT(11),
    ID_AVATAR INT(11),
    CONSTRAINT FK_USUARIO_PAIS FOREIGN KEY(ID_PAIS) REFERENCES PAIS(ID_PAIS),
    CONSTRAINT FK_USUARIO_AVATAR FOREIGN KEY(ID_AVATAR) REFERENCES AVATAR(ID_AVATAR)
);

CREATE TABLE PLAYLIST(
	ID_PLAYLIST INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    DATA_CRIACAO DATETIME,
	PRIVADO SMALLINT(6),
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_PLAYLIST_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE VIDEO(
	ID_VIDEO INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USUARIO_ID INT(11) NOT NULL,
    TITULO VARCHAR(100),
    DESCRICAO TEXT,
    TAMANHO DOUBLE,
    NOMEARQUIVO VARCHAR(100),
    DURACAO DOUBLE,
    IMAGEM VARCHAR(100),
    QTDREPRODUCOESE INT(11),
    QTDLIKES INT(11),
    QTDDISLIKES INT(11),
    PRIVADO SMALLINT(6),
    DATAPUBLICACAO DATETIME,
    CONSTRAINT FK_VIDEO_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE PLAYLIST_VIDEO(
	ID_VIDEO INT(11) NOT NULL AUTO_INCREMENT,
    ID_PLAYLIST INT(11) NOT NULL,
    CONSTRAINT FK_PLAYLIST_VIDEO_VIDEO FOREIGN KEY(ID_VIDEO) REFERENCES VIDEO(ID_VIDEO),
    CONSTRAINT FK_PLAYLIST_VIDEO_PLAYLIST FOREIGN KEY(ID_PLAYLIST) REFERENCES PLAYLIST(ID_PLAYLIST)
);

CREATE TABLE CANAL(
	ID_CANAL INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO TEXT,
    DATACRIACAO DATETIME,
    ID_USUARIO INT NOT NULL,
    CONSTRAINT FK_CANAL_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)    
);