-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 22:00:10 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema universoleitura
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema universoleitura
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `universoleitura` DEFAULT CHARACTER SET utf8 ;
USE `universoleitura` ;

-- -----------------------------------------------------
-- Table `universoleitura`.`associados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`associados` (
  `codId` INT NOT NULL AUTO_INCREMENT,
  `rg` CHAR(7) NULL DEFAULT NULL,
  `nome` VARCHAR(50) NULL DEFAULT NULL,
  `sobrenome` VARCHAR(50) NULL DEFAULT NULL,
  `endereco` VARCHAR(150) NULL DEFAULT NULL,
  `cidade` VARCHAR(50) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`codId`),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`autores` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `sobrenome` VARCHAR(100) NULL DEFAULT NULL,
  `nome` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`editoras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`editoras` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(150) NULL DEFAULT NULL,
  `telefone` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`emprestimos` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `codAssoc` INT NULL DEFAULT NULL,
  `data_` DATE NULL DEFAULT NULL,
  `prazo_devolucao` DATE NULL DEFAULT NULL,
  `data_devolucao` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK_EMPRESTIMOS_ASSOCIADOS_idx` (`codAssoc` ASC) VISIBLE,
  CONSTRAINT `FK_EMPRESTIMOS_ASSOCIADOS`
    FOREIGN KEY (`codAssoc`)
    REFERENCES `universoleitura`.`associados` (`codId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`livros` (
  `cod` INT NOT NULL AUTO_INCREMENT,
  `cod_ISBN` VARCHAR(13) NULL DEFAULT NULL,
  `titulo` VARCHAR(200) NULL DEFAULT NULL,
  `ano_criacao` YEAR NULL DEFAULT NULL,
  `cod_autor` INT NULL DEFAULT NULL,
  `ano_publicacao` YEAR NULL DEFAULT NULL,
  `cod_editora` INT NULL DEFAULT NULL,
  PRIMARY KEY (`cod`),
  INDEX `FK_LIVROS_AUTORES_idx` (`cod_autor` ASC) VISIBLE,
  INDEX `FK_LIVROS_EDITORAS_idx` (`cod_editora` ASC) VISIBLE,
  CONSTRAINT `FK_LIVROS_AUTORES`
    FOREIGN KEY (`cod_autor`)
    REFERENCES `universoleitura`.`autores` (`codigo`),
  CONSTRAINT `FK_LIVROS_EDITORAS`
    FOREIGN KEY (`cod_editora`)
    REFERENCES `universoleitura`.`editoras` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`exemplares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`exemplares` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cod_livro` INT NULL DEFAULT NULL,
  `sinistro` TINYINT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK_EXEMPLARES_LIVROS_idx` (`cod_livro` ASC) VISIBLE,
  CONSTRAINT `FK_EXEMPLARES_LIVROS`
    FOREIGN KEY (`cod_livro`)
    REFERENCES `universoleitura`.`livros` (`cod`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`emprestimo_exemplares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`emprestimo_exemplares` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `cod_emprestimo` INT NULL DEFAULT NULL,
  `cod_exemplar` INT NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `FK_EMPRESTIMO_EXEMPLARES_EXEMPLARES_idx` (`cod_exemplar` ASC) VISIBLE,
  INDEX `FK_EMPRESTIMO_EXEMPLARES_EMPRESTIMOS_idx` (`cod_emprestimo` ASC) VISIBLE,
  CONSTRAINT `FK_EMPRESTIMO_EXEMPLARES_EMPRESTIMOS`
    FOREIGN KEY (`cod_emprestimo`)
    REFERENCES `universoleitura`.`emprestimos` (`codigo`),
  CONSTRAINT `FK_EMPRESTIMO_EXEMPLARES_EXEMPLARES`
    FOREIGN KEY (`cod_exemplar`)
    REFERENCES `universoleitura`.`exemplares` (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `universoleitura`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `universoleitura`.`telefones` (
  `telefoneId` INT NOT NULL AUTO_INCREMENT,
  `telefone_socio` VARCHAR(100) NULL DEFAULT NULL,
  `codAssoc` INT NULL DEFAULT NULL,
  PRIMARY KEY (`telefoneId`),
  INDEX `FK_TELEFONES_ASSOCIADOS_idx` (`codAssoc` ASC) VISIBLE,
  CONSTRAINT `FK_TELEFONES_ASSOCIADOS`
    FOREIGN KEY (`codAssoc`)
    REFERENCES `universoleitura`.`associados` (`codId`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
